# Generated by Django 4.2.2 on 2023-07-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_description_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
