# Generated by Django 4.2.2 on 2023-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
