# Generated by Django 4.2.2 on 2023-07-19 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_description_alter_team_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
