# Generated by Django 4.2.2 on 2023-07-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='slug',
        ),
        migrations.AlterField(
            model_name='home',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
