# Generated by Django 4.2.2 on 2023-07-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_index_remove_home_slug_alter_home_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index',
        ),
    ]
