# Generated by Django 4.2.2 on 2023-07-17 11:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
