# Generated by Django 4.2.2 on 2023-07-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homesectiontwo_home_image_home_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeSectionTwo',
            new_name='HomeSectionOne',
        ),
    ]
