# Generated by Django 4.2.2 on 2023-07-25 21:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_homesectiontwo_homesectionone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSectionOne',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='image',
            new_name='image_section_one',
        ),
        migrations.AddField(
            model_name='home',
            name='content_section_one',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='image_url_section_one',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
