# Generated by Django 4.2.2 on 2023-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchdeck', '0002_pitchdeck_pmv_pitchdeck_raising_pitchdeck_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchdeck',
            name='assur',
        ),
        migrations.RemoveField(
            model_name='pitchdeck',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pitchdeck',
            name='location',
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='Assurance',
            field=models.CharField(choices=[('SEIS', 'SEIS'), ('EIS', 'EIS'), ('NONE', 'NONE')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='Sector',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='Email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='Location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
