# Generated by Django 4.2.2 on 2023-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchdeck', '0003_remove_pitchdeck_assur_remove_pitchdeck_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchdeck',
            name='PMV',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='Raising',
            field=models.BigIntegerField(default=None),
        ),
    ]
