# Generated by Django 4.2.2 on 2023-09-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchdeck', '0004_alter_pitchdeck_pmv_alter_pitchdeck_raising'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='Stage',
            field=models.CharField(choices=[('Ideation/Angel', 'Ideation/Angel'), ('Pre-Seed', 'Pre-Seed'), ('Seed', 'Seed'), ('Series-A', 'Series-A'), ('Series-B', 'Series-B'), ('Series-C', 'Series-C'), ('Series-D', 'Series-D'), ('Mezzanine Round', 'Mezzanine Round'), ('IPO', 'IPO')], default=None, max_length=20),
        ),
    ]
